import { demoStore } from './store';
import { expandAll } from '../calendar/recurrence';
import type { AskContext, HermesResult } from '../chat/hermesAdapter';

export const DEMO_REPLY_PREFIX = 'Demo scenario';
const currency = (value: number) => `$${Number(value).toLocaleString('en-CA')}`;

/** Deliberately bounded intent handling. Only explicit, named demo decisions
 * mutate state; a general sentence mentioning approval never authorizes one. */
export async function askDemo(text: string, ctx: AskContext): Promise<HermesResult> {
  if (ctx.signal?.aborted) return { ok: false, error: 'Cancelled.' };
  await new Promise<void>(resolve => {
    const done = () => { clearTimeout(timer); ctx.signal?.removeEventListener('abort', done); resolve(); };
    const timer = setTimeout(done, 450);
    ctx.signal?.addEventListener('abort', done, { once: true });
  });
  if (ctx.signal?.aborted) return { ok: false, error: 'Cancelled.' };
  const input = text.trim().toLowerCase();
  const get = async (table: string) => (await demoStore.from(table).select()).data;
  const monthly = (await get('msp_success_plans'))[0];
  const weekly = (await get('asap_plans'))[0];
  const clients = await get('asap_clients');
  const client = clients.find((c: { display_name: string }) => input.includes(c.display_name.split(' ')[0].toLowerCase()));
  let reply: string;
  if (/^(approve|hold|reject) (sarah[’']?s )?(buyer )?packet[.!]?$/.test(input)) {
    const approved = input.startsWith('approve');
    const result = await demoStore.rpc('decide_execution_approval', { p_log_id: 1, p_approved: approved });
    reply = result.error ? result.error.message : result.data === 0 ? 'That sample packet already has a decision. Reset the demo to try it again.' : `${approved ? 'Approved' : 'Held'} Sarah’s sample packet. Your decision is reflected on Home and in Memory. No client message was sent or appointment booked.`;
  } else if (ctx.attachments?.length) {
    reply = `${ctx.attachments.length} attached file${ctx.attachments.length === 1 ? '' : 's'} added as local previews. Their contents have not been uploaded or analysed. Live document processing will be connected in the backend phase. You can explore the prepared sample packet by asking “Show Sarah’s packet”.`;
  } else if (/monthly|income|goal|foundation/.test(input)) {
    reply = `Your sample monthly target is ${currency(monthly.goal_income)} in ${monthly.primary_market}, with an assumed ${currency(monthly.avg_commission)} commission per deal — ${Math.ceil(monthly.goal_income / monthly.avg_commission)} closings as a planning target.\n\nFocus: ${monthly.main_focus}. Bottleneck: ${monthly.bottleneck}. Capacity: ${monthly.hours_available} hours per week. These are fictional planning inputs, not achieved revenue.\n\nThis week: ${weekly.weekly_priority}`;
  } else if (/next week|weekly|last week|replan|retro/.test(input)) {
    const retro = (await get('asap_weekly_execution'))[0];
    reply = `The monthly foundation stays in place. This week’s priority is: ${weekly.weekly_priority}\n\nLast week’s sample record: ${retro.blocks_executed} of ${retro.blocks_scheduled} blocks executed. Win: ${retro.execution_win}\nBottleneck: ${retro.execution_bottleneck}\n\nThe illustrative next-week adjustment is to protect buyer follow-up and batch content into fewer blocks, while respecting appointments and available hours. No new plan has been generated by a live agent.`;
  } else if (/calendar|schedule|today|day|plate/.test(input) && !/book|send/.test(input)) {
    const events = await get('asap_calendar_events');
    const from = new Date(); from.setHours(0, 0, 0, 0);
    const to = new Date(from); to.setDate(to.getDate() + 1);
    const agenda = expandAll(events, { from, to });
    reply = `Your sample day:\n${agenda.map(o => `${o.allDay ? 'All day' : o.start.toLocaleTimeString('en-CA', { hour: 'numeric', minute: '2-digit' })} · ${o.event.title}${o.event.calendar_id === 'asap' ? ' — assistant preparation' : ''}`).join('\n')}\n\nUse Calendar to move or add a block. Personal commitments remain protected from agent work.`;
  } else if (client && /brief|budget|criteria|requirement/.test(input)) {
    const criteria = (await get('asap_client_criteria')).filter((r: { client_id: string }) => r.client_id === client.id);
    reply = `${client.display_name}’s current sample brief:\nBudget: ${currency(client.budget_min ?? 0)}–${currency(client.budget_max ?? 0)}.\n${criteria.map((r: { kind: string; label: string }) => `${r.kind === 'must' ? 'Must have' : r.kind === 'nice' ? 'Preference' : 'Deal breaker'}: ${r.label}`).join('\n')}\n\nEdit this brief in Clients. Scout recomputes fit using those requirements.`;
  } else if (/sarah|packet|shortlist|buyer|draft/.test(input) && !/\b(send|book|approve|reject|hold|delete)\b/.test(input)) {
    const row = (await get('asap_execution_log')).find((r: { id: number }) => r.id === 1);
    reply = `${row.artifact_text}\n\nThis is the original prepared sample. Current buyer criteria and matches are available in Clients and Scout. To record a local review decision, type “Approve Sarah’s packet” or “Hold Sarah’s packet”.`;
  } else {
    reply = `You asked: “${text.trim()}”. This frontend demo has no live agent connection, so I have not executed that request.\n\nTry “What is my monthly plan?”, “Explain next week”, “Show Sarah’s brief”, “Show Sarah’s packet”, or “What is on my calendar today?”. You can edit clients, shortlists, calendar blocks, and preferences directly in their tabs.`;
  }
  return { ok: true, text: `${DEMO_REPLY_PREFIX}\n\n${reply}`, actions: [] };
}
